library(swap2r)
invisible(rdinit("swap.swp"))
rdsrea("LAT")
message("Now DTMIN as real")
rdsrea("DTMIN")
message("Now DTMIN as double")
rdsdou("DTMIN")
message("Now PROJECT")
rdscha("PROJECT")
rdscha("PATHATM")
rdscha("METFIL")
rdarea("DZNEW")
rdadou("HSUBLAY")
rdinlv()
rdinne("DATET")
rdindt("DATET")
rdinar("DATET")
rdinar("PROJECT")
rdsint("SWERROR")
rdsint("SWYRVAR")
rdstim("TSTART")
rdatim("OUTDAT")

message("Opening file for writing")
wrinit("qq.tt")
message("writing")
wrscha("hello", "world")
message("Closing")
wrclose()

rdread("DATEFIX")
rdread("DZNEW")
rdread("PONDMX")
rdread("CROPNAME")
rdread("OUTDAT")
rdread("CROPSTART")
